const ACCEPTED_OSM_VALUES = {
  ADMINISTRATIVE: 'administrative',
  ARCHIPELAGO: 'archipelago',
  CITY: 'city',
  COUNTY: 'county',
  COUNTRY: 'country',
  DISTRICT: 'district',
  ISLAND: 'island',
  LOCALITY: 'locality',
  MUNICIPALITY: 'municipality',
  PROVINCE: 'province',
  REGION: 'region',
  STATE: 'state',
  TERRITORY: 'territory',
  TOWN: 'town',
  VILLAGE: 'village'
} as const

const COUNTRIES = {
  ALBANIA: 'Albania',
  BARBADOS: 'Barbados',
  BRUNEI: 'Brunei',
  CAPE_VERDE: 'Cape Verde',
  CAYMAN: 'Cayman Islands',
  CHINA: 'China',
  CROATIA: 'Croatia',
  CYPRUS: 'Cyprus',
  EL_SALVADOR: 'El Salvador',
  ESTONIA: 'Estonia',
  FRANCE: 'France',
  GREENLAND: 'Greenland',
  GRENADA: 'Grenada',
  GUERNSEY: 'Guernsey',
  HUNGARY: 'Hungary',
  ICELAND: 'Iceland',
  IRELAND: 'Ireland',
  ISLE_OF_MAN: 'Isle of Man',
  JAMAICA: 'Jamaica',
  JAPAN: 'Japan',
  KOSOVO: 'Kosovo',
  LATVIA: 'Latvia',
  LESOTHO: 'Lesotho',
  LIECHTENSTEIN: 'Liechtenstein',
  LUXEMBOURG: 'Luxembourg',
  MARSHALL_ISLANDS: 'Marshall Islands',
  MAURITIUS: 'Mauritius',
  MICRONESIA: 'Federated States of Micronesia',
  MOLDOVA: 'Moldova',
  MONTENEGRO: 'Montenegro',
  MONTSERRAT: 'Montserrat',
  NAURU: 'Nauru',
  NEPAL: 'Nepal',
  NETHERLANDS: 'Netherlands',
  NORWAY: 'Norway',
  OMAN: 'Oman',
  PALESINE: 'Palestinian Territory',
  PORTUGAL: 'Portugal',
  ROMANIA: 'Romania',
  RWANDA: 'Rwanda',
  SAO_TOME: 'São Tomé and Príncipe',
  SEYCHELLES: 'Seychelles',
  ST_KITTS_NEVIS: 'Saint Kitts and Nevis',
  ST_VINCENT_GRENADINES: 'Saint Vincent and the Grenadines',
  SWEDEN: 'Sweden',
  TAIWAN: 'Taiwan',
  TURKS_CAICOS: 'Turks and Caicos Islands',
  TUVALU: 'Tuvalu'
} as const

const PHOTON_LOCATION_TYPES = {
  CITY: 'city',
  COUNTY: 'county',
  STATE: 'state'
} as const

export { ACCEPTED_OSM_VALUES, COUNTRIES, PHOTON_LOCATION_TYPES }
